// megafunction wizard: %POS-PHY Level 2 and 3 Compiler v1.4.1%
// GENERATION: XML

// ============================================================
// Megafunction Name(s):
// 			auk_pac_mtx_mw
// ============================================================
// Generated by POS-PHY Level 2 and 3 Compiler 1.4.1 [Altera, IP Toolbench v1.2.11 build48]
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2007 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.


module spi3_tx /* synthesis altera_attribute="suppress_da_rule_internal=z100" */ (
	a_tfclk,
	a_treset_n,
	a_dtpa,
	b_clk,
	b_reset_n,
	b_dav,
	b_val,
	b_dat,
	b_sop,
	b_eop,
	b_err,
	b_mty,
	a_tenb,
	a_tdat,
	a_tsop,
	a_teop,
	a_terr,
	a_tmod,
	b_ena);


	input		a_tfclk;
	input		a_treset_n;
	input	[0:0]	a_dtpa;
	input		b_clk;
	input		b_reset_n;
	input		b_dav;
	input		b_val;
	input	[31:0]	b_dat;
	input		b_sop;
	input		b_eop;
	input		b_err;
	input	[1:0]	b_mty;
	output		a_tenb;
	output	[31:0]	a_tdat;
	output		a_tsop;
	output		a_teop;
	output		a_terr;
	output	[1:0]	a_tmod;
	output		b_ena;

	wire signal_wire0 = 1'b0;
	wire signal_wire1 = 1'b0;
	wire [7:0] signal_wire2 = 8'b0;
	wire signal_wire3 = 1'b0;
	wire [7:0] signal_wire4 = 8'b0;
	wire signal_wire5 = 1'b0;
	wire signal_wire6 = 1'b0;
	wire [7:0] signal_wire7 = 8'b0;
	wire signal_wire8 = 1'b0;
	wire signal_wire9 = 1'b0;
	wire signal_wire10 = 1'b0;
	wire signal_wire11 = 1'b0;
	wire signal_wire12 = 1'b0;
	wire [7:0] signal_wire13 = 8'b0;
	wire signal_wire14 = 1'b0;
	wire signal_wire15 = 1'b0;
	wire signal_wire16 = 1'b0;
	wire [7:0] signal_wire17 = 8'b0;
	wire signal_wire18 = 1'b0;
	wire signal_wire19 = 1'b0;
	wire signal_wire20 = 1'b0;
	wire [63:0] signal_wire21 = 64'b0;
	wire signal_wire22 = 1'b0;
	wire signal_wire23 = 1'b0;
	wire signal_wire24 = 1'b0;
	wire signal_wire25 = 1'b0;
	wire [3:0] signal_wire26 = 4'b0;
	wire signal_wire27 = 1'b0;
	wire signal_wire28 = 1'b0;
	wire [7:0] signal_wire29 = 8'b0;
	wire signal_wire30 = 1'b0;
	wire signal_wire31 = 1'b0;
	wire signal_wire32 = 1'b0;
	wire [7:0] signal_wire33 = 8'b0;
	wire signal_wire34 = 1'b0;
	wire signal_wire35 = 1'b0;
	wire signal_wire36 = 1'b0;
	wire [63:0] signal_wire37 = 64'b0;
	wire signal_wire38 = 1'b0;
	wire signal_wire39 = 1'b0;
	wire signal_wire40 = 1'b0;
	wire signal_wire41 = 1'b0;
	wire [3:0] signal_wire42 = 4'b0;
	wire signal_wire43 = 1'b0;
	wire signal_wire44 = 1'b0;
	wire [7:0] signal_wire45 = 8'b0;
	wire signal_wire46 = 1'b0;
	wire signal_wire47 = 1'b0;
	wire signal_wire48 = 1'b0;
	wire [7:0] signal_wire49 = 8'b0;
	wire signal_wire50 = 1'b0;
	wire signal_wire51 = 1'b0;
	wire signal_wire52 = 1'b0;
	wire [63:0] signal_wire53 = 64'b0;
	wire signal_wire54 = 1'b0;
	wire signal_wire55 = 1'b0;
	wire signal_wire56 = 1'b0;
	wire signal_wire57 = 1'b0;
	wire [3:0] signal_wire58 = 4'b0;
	wire signal_wire59 = 1'b0;
	wire signal_wire60 = 1'b0;
	wire [7:0] signal_wire61 = 8'b0;
	wire signal_wire62 = 1'b0;
	wire signal_wire63 = 1'b0;
	wire signal_wire64 = 1'b0;
	wire [7:0] signal_wire65 = 8'b0;
	wire signal_wire66 = 1'b0;
	wire signal_wire67 = 1'b0;
	wire signal_wire68 = 1'b0;
	wire [63:0] signal_wire69 = 64'b0;
	wire signal_wire70 = 1'b0;
	wire signal_wire71 = 1'b0;
	wire signal_wire72 = 1'b0;
	wire signal_wire73 = 1'b0;
	wire [3:0] signal_wire74 = 4'b0;
	wire signal_wire75 = 1'b0;
	wire signal_wire76 = 1'b0;
	wire [7:0] signal_wire77 = 8'b0;
	wire signal_wire78 = 1'b0;
	wire signal_wire79 = 1'b0;
	wire signal_wire80 = 1'b0;
	wire [7:0] signal_wire81 = 8'b0;
	wire signal_wire82 = 1'b0;
	wire signal_wire83 = 1'b0;
	wire signal_wire84 = 1'b0;
	wire [63:0] signal_wire85 = 64'b0;
	wire signal_wire86 = 1'b0;
	wire signal_wire87 = 1'b0;
	wire signal_wire88 = 1'b0;
	wire signal_wire89 = 1'b0;
	wire [3:0] signal_wire90 = 4'b0;
	wire signal_wire91 = 1'b0;
	wire signal_wire92 = 1'b0;
	wire [7:0] signal_wire93 = 8'b0;
	wire signal_wire94 = 1'b0;
	wire signal_wire95 = 1'b0;
	wire signal_wire96 = 1'b0;
	wire [7:0] signal_wire97 = 8'b0;
	wire signal_wire98 = 1'b0;
	wire signal_wire99 = 1'b0;
	wire signal_wire100 = 1'b0;
	wire [63:0] signal_wire101 = 64'b0;
	wire signal_wire102 = 1'b0;
	wire signal_wire103 = 1'b0;
	wire signal_wire104 = 1'b0;
	wire signal_wire105 = 1'b0;
	wire [3:0] signal_wire106 = 4'b0;
	wire signal_wire107 = 1'b0;
	wire signal_wire108 = 1'b0;
	wire [7:0] signal_wire109 = 8'b0;
	wire signal_wire110 = 1'b0;
	wire signal_wire111 = 1'b0;
	wire signal_wire112 = 1'b0;
	wire [7:0] signal_wire113 = 8'b0;
	wire signal_wire114 = 1'b0;
	wire signal_wire115 = 1'b0;
	wire signal_wire116 = 1'b0;
	wire [63:0] signal_wire117 = 64'b0;
	wire signal_wire118 = 1'b0;
	wire signal_wire119 = 1'b0;
	wire signal_wire120 = 1'b0;
	wire signal_wire121 = 1'b0;
	wire [3:0] signal_wire122 = 4'b0;
	wire [31:0] signal_wire123 = 32'h00000001;
	wire [31:0] signal_wire124 = 32'h00000002;
	wire [31:0] signal_wire125 = 32'h00000003;
	wire [31:0] signal_wire126 = 32'h00000004;
	wire [31:0] signal_wire127 = 32'h00000005;
	wire [31:0] signal_wire128 = 32'h00000006;
	wire [31:0] signal_wire129 = 32'h00000007;
	wire [31:0] signal_wire130 = 32'h00000008;
	wire [31:0] signal_wire131 = 32'h00000009;
	wire [31:0] signal_wire132 = 32'h0000000a;
	wire [31:0] signal_wire133 = 32'h0000000b;
	wire [31:0] signal_wire134 = 32'h0000000c;
	wire [31:0] signal_wire135 = 32'h0000000d;
	wire [31:0] signal_wire136 = 32'h0000000e;
	wire [31:0] signal_wire137 = 32'h0000000f;
	wire [31:0] signal_wire138 = 32'h00000010;
	wire [31:0] signal_wire139 = 32'h00000011;
	wire [15:0] signal_wire140 = 16'h0008;
	wire [15:0] signal_wire141 = 16'h0008;
	wire [15:0] signal_wire142 = 16'h0008;
	wire [15:0] signal_wire143 = 16'h0008;
	wire [15:0] signal_wire144 = 16'h0004;
	wire [15:0] signal_wire145 = 16'h0000;
	wire [15:0] signal_wire146 = 16'h000d;
	wire [15:0] signal_wire147 = 16'h0008;
	wire [15:0] signal_wire148 = 16'h0012;
	wire [15:0] signal_wire149 = 16'b0;
	wire [15:0] signal_wire150 = 16'b0;
	wire [15:0] signal_wire151 = 16'b0;
	wire [15:0] signal_wire152 = 16'b0;
	wire [15:0] signal_wire153 = 16'b0;
	wire [15:0] signal_wire154 = 16'b0;
	wire [15:0] signal_wire155 = 16'b0;
	wire [15:0] signal_wire156 = 16'b0;
	wire [15:0] signal_wire157 = 16'b0;
	wire [15:0] signal_wire158 = 16'b0;
	wire [15:0] signal_wire159 = 16'b0;
	wire [15:0] signal_wire160 = 16'b0;
	wire [15:0] signal_wire161 = 16'b0;
	wire [15:0] signal_wire162 = 16'b0;
	wire [15:0] signal_wire163 = 16'b0;
	wire [15:0] signal_wire164 = 16'b0;
	wire [15:0] signal_wire165 = 16'b0;
	wire [15:0] signal_wire166 = 16'b0;
	wire [15:0] signal_wire167 = 16'b0;
	wire [15:0] signal_wire168 = 16'b0;
	wire [15:0] signal_wire169 = 16'b0;
	wire [15:0] signal_wire170 = 16'b0;
	wire [15:0] signal_wire171 = 16'b0;
	wire [15:0] signal_wire172 = 16'b0;
	wire [15:0] signal_wire173 = 16'b0;
	wire [15:0] signal_wire174 = 16'b0;
	wire [15:0] signal_wire175 = 16'b0;
	wire [15:0] signal_wire176 = 16'b0;
	wire [15:0] signal_wire177 = 16'b0;
	wire [15:0] signal_wire178 = 16'b0;
	wire [15:0] signal_wire179 = 16'b0;
	wire [15:0] signal_wire180 = 16'b0;
	wire [15:0] signal_wire181 = 16'b0;
	wire [15:0] signal_wire182 = 16'b0;
	wire [15:0] signal_wire183 = 16'b0;
	wire [15:0] signal_wire184 = 16'b0;
	wire [15:0] signal_wire185 = 16'b0;
	wire [15:0] signal_wire186 = 16'b0;
	wire [15:0] signal_wire187 = 16'b0;
	wire [15:0] signal_wire188 = 16'b0;
	wire [15:0] signal_wire189 = 16'b0;
	wire [15:0] signal_wire190 = 16'b0;
	wire [15:0] signal_wire191 = 16'b0;
	wire [15:0] signal_wire192 = 16'b0;
	wire [15:0] signal_wire193 = 16'b0;
	wire [15:0] signal_wire194 = 16'b0;
	wire [15:0] signal_wire195 = 16'b0;
	wire [15:0] signal_wire196 = 16'b0;
	wire [15:0] signal_wire197 = 16'b0;

	auk_pac_mtx_mw	auk_pac_mtx_mw_inst(
		.clka(a_tfclk),
		.reseta(a_treset_n),
		.dpav_ina(a_dtpa),
		.ppav_ina(signal_wire0),
		.spav_ina(signal_wire1),
		.addr_ina(signal_wire2),
		.rd_ina(signal_wire3),
		.clkb1(b_clk),
		.resetb1(b_reset_n),
		.dpav_inb1(signal_wire4),
		.ppav_inb1(signal_wire5),
		.spav_inb1(signal_wire6),
		.dav_inb1(b_dav),
		.addr_inb1(signal_wire7),
		.wr_inb1(signal_wire8),
		.val_inb1(b_val),
		.sx_inb1(signal_wire9),
		.data_inb1(b_dat),
		.sop_inb1(b_sop),
		.eop_inb1(b_eop),
		.err_inb1(b_err),
		.prty_inb1(signal_wire10),
		.mod_inb1(b_mty),
		.clkb2(signal_wire11),
		.resetb2(signal_wire12),
		.dpav_inb2(signal_wire13),
		.ppav_inb2(signal_wire14),
		.spav_inb2(signal_wire15),
		.dav_inb2(signal_wire16),
		.addr_inb2(signal_wire17),
		.wr_inb2(signal_wire18),
		.val_inb2(signal_wire19),
		.sx_inb2(signal_wire20),
		.data_inb2(signal_wire21),
		.sop_inb2(signal_wire22),
		.eop_inb2(signal_wire23),
		.err_inb2(signal_wire24),
		.prty_inb2(signal_wire25),
		.mod_inb2(signal_wire26),
		.clkb3(signal_wire27),
		.resetb3(signal_wire28),
		.dpav_inb3(signal_wire29),
		.ppav_inb3(signal_wire30),
		.spav_inb3(signal_wire31),
		.dav_inb3(signal_wire32),
		.addr_inb3(signal_wire33),
		.wr_inb3(signal_wire34),
		.val_inb3(signal_wire35),
		.sx_inb3(signal_wire36),
		.data_inb3(signal_wire37),
		.sop_inb3(signal_wire38),
		.eop_inb3(signal_wire39),
		.err_inb3(signal_wire40),
		.prty_inb3(signal_wire41),
		.mod_inb3(signal_wire42),
		.clkb4(signal_wire43),
		.resetb4(signal_wire44),
		.dpav_inb4(signal_wire45),
		.ppav_inb4(signal_wire46),
		.spav_inb4(signal_wire47),
		.dav_inb4(signal_wire48),
		.addr_inb4(signal_wire49),
		.wr_inb4(signal_wire50),
		.val_inb4(signal_wire51),
		.sx_inb4(signal_wire52),
		.data_inb4(signal_wire53),
		.sop_inb4(signal_wire54),
		.eop_inb4(signal_wire55),
		.err_inb4(signal_wire56),
		.prty_inb4(signal_wire57),
		.mod_inb4(signal_wire58),
		.clkb5(signal_wire59),
		.resetb5(signal_wire60),
		.dpav_inb5(signal_wire61),
		.ppav_inb5(signal_wire62),
		.spav_inb5(signal_wire63),
		.dav_inb5(signal_wire64),
		.addr_inb5(signal_wire65),
		.wr_inb5(signal_wire66),
		.val_inb5(signal_wire67),
		.sx_inb5(signal_wire68),
		.data_inb5(signal_wire69),
		.sop_inb5(signal_wire70),
		.eop_inb5(signal_wire71),
		.err_inb5(signal_wire72),
		.prty_inb5(signal_wire73),
		.mod_inb5(signal_wire74),
		.clkb6(signal_wire75),
		.resetb6(signal_wire76),
		.dpav_inb6(signal_wire77),
		.ppav_inb6(signal_wire78),
		.spav_inb6(signal_wire79),
		.dav_inb6(signal_wire80),
		.addr_inb6(signal_wire81),
		.wr_inb6(signal_wire82),
		.val_inb6(signal_wire83),
		.sx_inb6(signal_wire84),
		.data_inb6(signal_wire85),
		.sop_inb6(signal_wire86),
		.eop_inb6(signal_wire87),
		.err_inb6(signal_wire88),
		.prty_inb6(signal_wire89),
		.mod_inb6(signal_wire90),
		.clkb7(signal_wire91),
		.resetb7(signal_wire92),
		.dpav_inb7(signal_wire93),
		.ppav_inb7(signal_wire94),
		.spav_inb7(signal_wire95),
		.dav_inb7(signal_wire96),
		.addr_inb7(signal_wire97),
		.wr_inb7(signal_wire98),
		.val_inb7(signal_wire99),
		.sx_inb7(signal_wire100),
		.data_inb7(signal_wire101),
		.sop_inb7(signal_wire102),
		.eop_inb7(signal_wire103),
		.err_inb7(signal_wire104),
		.prty_inb7(signal_wire105),
		.mod_inb7(signal_wire106),
		.clkb8(signal_wire107),
		.resetb8(signal_wire108),
		.dpav_inb8(signal_wire109),
		.ppav_inb8(signal_wire110),
		.spav_inb8(signal_wire111),
		.dav_inb8(signal_wire112),
		.addr_inb8(signal_wire113),
		.wr_inb8(signal_wire114),
		.val_inb8(signal_wire115),
		.sx_inb8(signal_wire116),
		.data_inb8(signal_wire117),
		.sop_inb8(signal_wire118),
		.eop_inb8(signal_wire119),
		.err_inb8(signal_wire120),
		.prty_inb8(signal_wire121),
		.mod_inb8(signal_wire122),
		.custom_ina0(signal_wire123),
		.custom_ina1(signal_wire124),
		.custom_inb1(signal_wire125),
		.custom_ina2(signal_wire126),
		.custom_inb2(signal_wire127),
		.custom_ina3(signal_wire128),
		.custom_inb3(signal_wire129),
		.custom_ina4(signal_wire130),
		.custom_inb4(signal_wire131),
		.custom_ina5(signal_wire132),
		.custom_inb5(signal_wire133),
		.custom_ina6(signal_wire134),
		.custom_inb6(signal_wire135),
		.custom_ina7(signal_wire136),
		.custom_inb7(signal_wire137),
		.custom_ina8(signal_wire138),
		.custom_inb8(signal_wire139),
		.a_fifo_burst(signal_wire140),
		.a_remote_burst(signal_wire141),
		.b1_fifo_burst(signal_wire142),
		.b1_remote_burst(signal_wire143),
		.b1_master_full_thresh(signal_wire144),
		.b1_empty_on_thresh(signal_wire145),
		.b1_empty_off_thresh(signal_wire146),
		.b1_full_on_thresh(signal_wire147),
		.b1_full_off_thresh(signal_wire148),
		.b2_fifo_burst(signal_wire149),
		.b2_remote_burst(signal_wire150),
		.b2_master_full_thresh(signal_wire151),
		.b2_empty_on_thresh(signal_wire152),
		.b2_empty_off_thresh(signal_wire153),
		.b2_full_on_thresh(signal_wire154),
		.b2_full_off_thresh(signal_wire155),
		.b3_fifo_burst(signal_wire156),
		.b3_remote_burst(signal_wire157),
		.b3_master_full_thresh(signal_wire158),
		.b3_empty_on_thresh(signal_wire159),
		.b3_empty_off_thresh(signal_wire160),
		.b3_full_on_thresh(signal_wire161),
		.b3_full_off_thresh(signal_wire162),
		.b4_fifo_burst(signal_wire163),
		.b4_remote_burst(signal_wire164),
		.b4_master_full_thresh(signal_wire165),
		.b4_empty_on_thresh(signal_wire166),
		.b4_empty_off_thresh(signal_wire167),
		.b4_full_on_thresh(signal_wire168),
		.b4_full_off_thresh(signal_wire169),
		.b5_fifo_burst(signal_wire170),
		.b5_remote_burst(signal_wire171),
		.b5_master_full_thresh(signal_wire172),
		.b5_empty_on_thresh(signal_wire173),
		.b5_empty_off_thresh(signal_wire174),
		.b5_full_on_thresh(signal_wire175),
		.b5_full_off_thresh(signal_wire176),
		.b6_fifo_burst(signal_wire177),
		.b6_remote_burst(signal_wire178),
		.b6_master_full_thresh(signal_wire179),
		.b6_empty_on_thresh(signal_wire180),
		.b6_empty_off_thresh(signal_wire181),
		.b6_full_on_thresh(signal_wire182),
		.b6_full_off_thresh(signal_wire183),
		.b7_fifo_burst(signal_wire184),
		.b7_remote_burst(signal_wire185),
		.b7_master_full_thresh(signal_wire186),
		.b7_empty_on_thresh(signal_wire187),
		.b7_empty_off_thresh(signal_wire188),
		.b7_full_on_thresh(signal_wire189),
		.b7_full_off_thresh(signal_wire190),
		.b8_fifo_burst(signal_wire191),
		.b8_remote_burst(signal_wire192),
		.b8_master_full_thresh(signal_wire193),
		.b8_empty_on_thresh(signal_wire194),
		.b8_empty_off_thresh(signal_wire195),
		.b8_full_on_thresh(signal_wire196),
		.b8_full_off_thresh(signal_wire197),
		.wr_outa(a_tenb),
		.data_outa(a_tdat),
		.sop_outa(a_tsop),
		.eop_outa(a_teop),
		.err_outa(a_terr),
		.mod_outa(a_tmod),
		.rd_outb1(b_ena));

	defparam
		auk_pac_mtx_mw_inst.gio_number_of_interface_a = 1,
		auk_pac_mtx_mw_inst.gio_number_of_interface_b = 1,
		auk_pac_mtx_mw_inst.gio_number_of_fifo = 1,
		auk_pac_mtx_mw_inst.gio_bus_mode = "1 2",
		auk_pac_mtx_mw_inst.gio_bus_level = "2 2",
		auk_pac_mtx_mw_inst.gio_bus_type = "0 0",
		auk_pac_mtx_mw_inst.gio_bus_direction = "0 1",
		auk_pac_mtx_mw_inst.gio_address_channels = "1 1",
		auk_pac_mtx_mw_inst.gio_address_range = "0 1",
		auk_pac_mtx_mw_inst.gio_address_width = "0 0",
		auk_pac_mtx_mw_inst.gio_address_style = "0 0",
		auk_pac_mtx_mw_inst.gio_base_address = "0 0",
		auk_pac_mtx_mw_inst.gio_address_mask = "0 0",
		auk_pac_mtx_mw_inst.gio_transfer_mode = "0 0",
		auk_pac_mtx_mw_inst.gio_dpav_range = "1 0",
		auk_pac_mtx_mw_inst.gio_spav_present = "1 0",
		auk_pac_mtx_mw_inst.gio_ppav_present = "0 0",
		auk_pac_mtx_mw_inst.gio_ddav_range = "1 1",
		auk_pac_mtx_mw_inst.gio_sx_present = "0 0",
		auk_pac_mtx_mw_inst.gio_val_present = "1 1",
		auk_pac_mtx_mw_inst.gio_eop_present = "1 1",
		auk_pac_mtx_mw_inst.gio_mod_present = "1 1",
		auk_pac_mtx_mw_inst.gio_data_width = "32 32",
		auk_pac_mtx_mw_inst.gio_prty_error_mode = "1 1",
		auk_pac_mtx_mw_inst.gio_prty_present = "0 0",
		auk_pac_mtx_mw_inst.gio_prty_mode = "0 0",
		auk_pac_mtx_mw_inst.gfifo_addr_range = "0 0",
		auk_pac_mtx_mw_inst.gfifo_depth = "0 128",
		auk_pac_mtx_mw_inst.gfifo_sync = "0 0",
		auk_pac_mtx_mw_inst.gio_fifo_burst = "8 8",
		auk_pac_mtx_mw_inst.gio_remote_burst = "8 8",
		auk_pac_mtx_mw_inst.gio_full_on_thresh = "0 8",
		auk_pac_mtx_mw_inst.gio_full_off_thresh = "0 18",
		auk_pac_mtx_mw_inst.gio_empty_on_thresh = "0 0",
		auk_pac_mtx_mw_inst.gio_empty_off_thresh = "0 13",
		auk_pac_mtx_mw_inst.gio_master_full_thresh = "0 4",
		auk_pac_mtx_mw_inst.gio_master_empty_thresh = "0 4",
		auk_pac_mtx_mw_inst.gio_mux_present = "1 0",
		auk_pac_mtx_mw_inst.gio_conva_present = "0 1",
		auk_pac_mtx_mw_inst.gio_convb_present = "0 0",
		auk_pac_mtx_mw_inst.gfifo_present = "0 1",
		auk_pac_mtx_mw_inst.gio_master_rd_dav_present = "1 1",
		auk_pac_mtx_mw_inst.gio_master_val_in_present = "1 1",
		auk_pac_mtx_mw_inst.gio_master_halt_on_val = "1 1",
		auk_pac_mtx_mw_inst.gio_data_out_zero = "0 0",
		auk_pac_mtx_mw_inst.gio_dumb_mode = "0 0",
		auk_pac_mtx_mw_inst.gio_speculative_read = "1 1",
		auk_pac_mtx_mw_inst.gio_custom_mode = "0 0",
		auk_pac_mtx_mw_inst.gio_reset = "0 0",
		auk_pac_mtx_mw_inst.gio_usesignals = 0,
		auk_pac_mtx_mw_inst.gdevice = 7,
		auk_pac_mtx_mw_inst.gdpav_width_in0 = 1,
		auk_pac_mtx_mw_inst.gdpav_width_out0 = 1,
		auk_pac_mtx_mw_inst.gaddr_width_out0 = 1,
		auk_pac_mtx_mw_inst.gdata_width0 = 32,
		auk_pac_mtx_mw_inst.gmod_width0 = 2,
		auk_pac_mtx_mw_inst.gdpav_width_out1 = 1,
		auk_pac_mtx_mw_inst.gaddr_width_out1 = 1,
		auk_pac_mtx_mw_inst.gdata_width1 = 32,
		auk_pac_mtx_mw_inst.gmod_width1 = 2,
		auk_pac_mtx_mw_inst.gdpav_width_in2 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_out2 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in2 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_out2 = 8,
		auk_pac_mtx_mw_inst.gdata_width2 = 64,
		auk_pac_mtx_mw_inst.gmod_width2 = 4,
		auk_pac_mtx_mw_inst.gdpav_width_in3 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_out3 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in3 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_out3 = 8,
		auk_pac_mtx_mw_inst.gdata_width3 = 64,
		auk_pac_mtx_mw_inst.gmod_width3 = 4,
		auk_pac_mtx_mw_inst.gdpav_width_in4 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_out4 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in4 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_out4 = 8,
		auk_pac_mtx_mw_inst.gdata_width4 = 64,
		auk_pac_mtx_mw_inst.gmod_width4 = 4,
		auk_pac_mtx_mw_inst.gdpav_width_in5 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_out5 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in5 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_out5 = 8,
		auk_pac_mtx_mw_inst.gdata_width5 = 64,
		auk_pac_mtx_mw_inst.gmod_width5 = 4,
		auk_pac_mtx_mw_inst.gdpav_width_in6 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_out6 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in6 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_out6 = 8,
		auk_pac_mtx_mw_inst.gdata_width6 = 64,
		auk_pac_mtx_mw_inst.gmod_width6 = 4,
		auk_pac_mtx_mw_inst.gdpav_width_in7 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_out7 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in7 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_out7 = 8,
		auk_pac_mtx_mw_inst.gdata_width7 = 64,
		auk_pac_mtx_mw_inst.gmod_width7 = 4,
		auk_pac_mtx_mw_inst.gdpav_width_in8 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_out8 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in8 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_out8 = 8,
		auk_pac_mtx_mw_inst.gdata_width8 = 64,
		auk_pac_mtx_mw_inst.gmod_width8 = 4,
		auk_pac_mtx_mw_inst.gaddr_width_in0 = 8,
		auk_pac_mtx_mw_inst.gdpav_width_in1 = 8,
		auk_pac_mtx_mw_inst.gaddr_width_in1 = 8;
endmodule

// =========================================================
// POS-PHY Level 2 and 3 Compiler Wizard Data
// ===============================
// DO NOT EDIT FOLLOWING DATA
// @Altera, IP Toolbench@
// Warning: If you modify this section, POS-PHY Level 2 and 3 Compiler Wizard may not be able to reproduce your chosen configuration.
// 
// Retrieval info: <?xml version="1.0"?>
// Retrieval info: <MEGACORE title="POS-PHY Level 2 and 3 Compiler"  version="1.4.1"  iptb_version="v1.2.11 build48"  format_version="120" >
// Retrieval info:  <NETLIST_SECTION active_core="auk_pac_mtx_mw" >
// Retrieval info:   <STATIC_SECTION>
// Retrieval info:    <PRIVATES>
// Retrieval info:     <NAMESPACE name = "parameterization">
// Retrieval info:      <PRIVATE name = "devicefamily" value="Cyclone II"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_INTERFACE_TYPE" value="ATL_SLV"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_BUS_WIDTH" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_PARITY_MODE" value="NONE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_PAR_ERR_ON_ERR_PIN" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_NO_FIFO" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_ADD_CONVB" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_FIFO_SIZE" value="512"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_FIFO_THRESHOLD" value="64"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_FIFO_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_FIFO_REMOTE_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_ADDRESS_MODE" value="DIRECT_SINGLE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_SX_ALWAYS" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_BASE_ADDRESS" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_DISABLE_SXPA" value="1"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B2_FIFO_SYNC" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "BUS_DIRECTION" value="TX"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "B_PORT_COUNT" value="1"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "COMMON_B_CLK_AND_RESET" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_INTERFACE_TYPE" value="PL3_LNK"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_BUS_WIDTH" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_PARITY_MODE" value="NONE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_PAR_ERR_ON_ERR_PIN" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_THRESHOLD" value="64"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_BURST" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_REMOTE_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_ADDRESS_MODE" value="DIRECT_SINGLE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_SX_ALWAYS" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_BASE_ADDRESS" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_DISABLE_SXPA" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_SYNC" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "FIFO_OVERFLOW" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "gdevice" value="7"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_INTERFACE_TYPE" value="ATL_MST"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_BUS_WIDTH" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_PARITY_MODE" value="NONE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_PAR_ERR_ON_ERR_PIN" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_NO_FIFO" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_ADD_CONVB" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_SIZE" value="512"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_THRESHOLD" value="64"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_REMOTE_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_ADDRESS_MODE" value="DIRECT_SINGLE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_SX_ALWAYS" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_BASE_ADDRESS" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_DISABLE_SXPA" value="1"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_SYNC" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "gio_custom" value="0 0 0 0 0 0 0 0 0"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "gio_usesignals" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "simgen_enable">
// Retrieval info:      <PRIVATE name = "language" value="Verilog HDL"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "simgen">
// Retrieval info:      <PRIVATE name = "filename" value="spi3_tx.vo"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "quartus_settings">
// Retrieval info:      <PRIVATE name = "DEVICE" value="AUTO"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "FAMILY" value="Cyclone II"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "serializer"/>
// Retrieval info:    </PRIVATES>
// Retrieval info:    <FILES/>
// Retrieval info:    <CONSTANTS>
// Retrieval info:     <CONSTANT name = "gio_number_of_interface_a" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gio_number_of_interface_b" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gio_number_of_fifo" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gio_bus_mode" value="1 2"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_bus_level" value="2 2"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_bus_type" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_bus_direction" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_channels" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_range" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_width" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_style" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_base_address" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_mask" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_transfer_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_dpav_range" value="1 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_spav_present" value="1 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_ppav_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_ddav_range" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_sx_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_val_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_eop_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_mod_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_data_width" value="32 32"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_prty_error_mode" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_prty_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_prty_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_addr_range" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_depth" value="0 128"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_sync" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_fifo_burst" value="8 8"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_remote_burst" value="8 8"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_full_on_thresh" value="0 8"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_full_off_thresh" value="0 18"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_empty_on_thresh" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_empty_off_thresh" value="0 13"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_full_thresh" value="0 4"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_empty_thresh" value="0 4"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_mux_present" value="1 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_conva_present" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_convb_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_present" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_rd_dav_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_val_in_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_halt_on_val" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_data_out_zero" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_dumb_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_speculative_read" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_custom_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_reset" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_usesignals" value="0"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdevice" value="7"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in0" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out0" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out0" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width0" value="32"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width0" value="2"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out1" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out1" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width1" value="32"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width1" value="2"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width2" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width2" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width3" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width3" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width4" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width4" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width5" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width5" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width6" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width6" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width7" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width7" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width8" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width8" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in0" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in1" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in1" value="8"  type="INTEGER" />
// Retrieval info:    </CONSTANTS>
// Retrieval info:    <PORTS>
// Retrieval info:     <PORT name = "clka" direction="INPUT"  connect_to="a_tfclk"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "reseta" direction="INPUT"  connect_to="a_treset_n"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_ina" direction="INPUT"  connect_to="a_dtpa"  default="NODEFVAL"  high_width="0"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "wr_outa" direction="OUTPUT"  connect_to="a_tenb"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_outa" direction="OUTPUT"  connect_to="a_tdat"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_outa" direction="OUTPUT"  connect_to="a_tsop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_outa" direction="OUTPUT"  connect_to="a_teop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_outa" direction="OUTPUT"  connect_to="a_terr"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_outa" direction="OUTPUT"  connect_to="a_tmod"  default="NODEFVAL"  high_width="1"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb1" direction="INPUT"  connect_to="b_clk"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb1" direction="INPUT"  connect_to="b_reset_n"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb1" direction="INPUT"  connect_to="b_dav"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb1" direction="INPUT"  connect_to="b_val"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb1" direction="INPUT"  connect_to="b_dat"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb1" direction="INPUT"  connect_to="b_sop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb1" direction="INPUT"  connect_to="b_eop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb1" direction="INPUT"  connect_to="b_err"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb1" direction="INPUT"  connect_to="b_mty"  default="NODEFVAL"  high_width="1"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_outb1" direction="OUTPUT"  connect_to="b_ena"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="63"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="3"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="63"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="3"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="63"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="3"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="63"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="3"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="63"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="3"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="63"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="3"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="63"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="3"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina0" direction="INPUT"  connect_to=" 1"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina1" direction="INPUT"  connect_to=" 2"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb1" direction="INPUT"  connect_to=" 3"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina2" direction="INPUT"  connect_to=" 4"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb2" direction="INPUT"  connect_to=" 5"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina3" direction="INPUT"  connect_to=" 6"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb3" direction="INPUT"  connect_to=" 7"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina4" direction="INPUT"  connect_to=" 8"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb4" direction="INPUT"  connect_to=" 9"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina5" direction="INPUT"  connect_to=" 10"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb5" direction="INPUT"  connect_to=" 11"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina6" direction="INPUT"  connect_to=" 12"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb6" direction="INPUT"  connect_to=" 13"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina7" direction="INPUT"  connect_to=" 14"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb7" direction="INPUT"  connect_to=" 15"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina8" direction="INPUT"  connect_to=" 16"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb8" direction="INPUT"  connect_to=" 17"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "a_fifo_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "a_remote_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_fifo_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_remote_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_master_full_thresh" direction="INPUT"  connect_to="4"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_empty_on_thresh" direction="INPUT"  connect_to="0"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_empty_off_thresh" direction="INPUT"  connect_to="13"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_full_on_thresh" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_full_off_thresh" direction="INPUT"  connect_to="18"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:    </PORTS>
// Retrieval info:    <LIBRARIES/>
// Retrieval info:   </STATIC_SECTION>
// Retrieval info:  </NETLIST_SECTION>
// Retrieval info: </MEGACORE>
// =========================================================
// RELATED_FILES: spi3_tx.v;
// IPFS_FILES: none;
// =========================================================
