// megafunction wizard: %POS-PHY Level 2 and 3 Compiler v1.4.1%
// GENERATION: XML

// ============================================================
// Megafunction Name(s):
// 			auk_pac_mrx_mw
// ============================================================
// Generated by POS-PHY Level 2 and 3 Compiler 1.4.1 [Altera, IP Toolbench v1.2.11 build48]
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2007 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.


module spi3_rx /* synthesis altera_attribute="suppress_da_rule_internal=z100" */ (
	a_rfclk,
	a_rreset_n,
	a_rval,
	a_rdat,
	a_rsop,
	a_reop,
	a_rerr,
	a_rmod,
	b_clk,
	b_reset_n,
	b_ena,
	a_renb,
	b_dav,
	b_val,
	b_dat,
	b_sop,
	b_eop,
	b_err,
	b_mty);


	input		a_rfclk;
	input		a_rreset_n;
	input		a_rval;
	input	[31:0]	a_rdat;
	input		a_rsop;
	input		a_reop;
	input		a_rerr;
	input	[1:0]	a_rmod;
	input		b_clk;
	input		b_reset_n;
	input		b_ena;
	output		a_renb;
	output		b_dav;
	output		b_val;
	output	[31:0]	b_dat;
	output		b_sop;
	output		b_eop;
	output		b_err;
	output	[1:0]	b_mty;

	wire [7:0] signal_wire0 = 8'b0;
	wire signal_wire1 = 1'b0;
	wire signal_wire2 = 1'b0;
	wire [7:0] signal_wire3 = 8'b0;
	wire signal_wire4 = 1'b0;
	wire signal_wire5 = 1'b0;
	wire signal_wire6 = 1'b0;
	wire [7:0] signal_wire7 = 8'b0;
	wire signal_wire8 = 1'b0;
	wire signal_wire9 = 1'b0;
	wire signal_wire10 = 1'b0;
	wire [7:0] signal_wire11 = 8'b0;
	wire signal_wire12 = 1'b0;
	wire signal_wire13 = 1'b0;
	wire [7:0] signal_wire14 = 8'b0;
	wire signal_wire15 = 1'b0;
	wire signal_wire16 = 1'b0;
	wire signal_wire17 = 1'b0;
	wire [7:0] signal_wire18 = 8'b0;
	wire signal_wire19 = 1'b0;
	wire signal_wire20 = 1'b0;
	wire signal_wire21 = 1'b0;
	wire [7:0] signal_wire22 = 8'b0;
	wire signal_wire23 = 1'b0;
	wire signal_wire24 = 1'b0;
	wire signal_wire25 = 1'b0;
	wire [7:0] signal_wire26 = 8'b0;
	wire signal_wire27 = 1'b0;
	wire signal_wire28 = 1'b0;
	wire signal_wire29 = 1'b0;
	wire [7:0] signal_wire30 = 8'b0;
	wire signal_wire31 = 1'b0;
	wire signal_wire32 = 1'b0;
	wire signal_wire33 = 1'b0;
	wire [7:0] signal_wire34 = 8'b0;
	wire signal_wire35 = 1'b0;
	wire signal_wire36 = 1'b0;
	wire signal_wire37 = 1'b0;
	wire [7:0] signal_wire38 = 8'b0;
	wire signal_wire39 = 1'b0;
	wire signal_wire40 = 1'b0;
	wire signal_wire41 = 1'b0;
	wire [7:0] signal_wire42 = 8'b0;
	wire signal_wire43 = 1'b0;
	wire signal_wire44 = 1'b0;
	wire signal_wire45 = 1'b0;
	wire [7:0] signal_wire46 = 8'b0;
	wire signal_wire47 = 1'b0;
	wire signal_wire48 = 1'b0;
	wire signal_wire49 = 1'b0;
	wire [7:0] signal_wire50 = 8'b0;
	wire signal_wire51 = 1'b0;
	wire signal_wire52 = 1'b0;
	wire signal_wire53 = 1'b0;
	wire [7:0] signal_wire54 = 8'b0;
	wire signal_wire55 = 1'b0;
	wire signal_wire56 = 1'b0;
	wire signal_wire57 = 1'b0;
	wire [7:0] signal_wire58 = 8'b0;
	wire signal_wire59 = 1'b0;
	wire signal_wire60 = 1'b0;
	wire signal_wire61 = 1'b0;
	wire [7:0] signal_wire62 = 8'b0;
	wire signal_wire63 = 1'b0;
	wire signal_wire64 = 1'b0;
	wire signal_wire65 = 1'b0;
	wire [7:0] signal_wire66 = 8'b0;
	wire signal_wire67 = 1'b0;
	wire [31:0] signal_wire68 = 32'h00000001;
	wire [31:0] signal_wire69 = 32'h00000002;
	wire [31:0] signal_wire70 = 32'h00000003;
	wire [31:0] signal_wire71 = 32'h00000004;
	wire [31:0] signal_wire72 = 32'h00000005;
	wire [31:0] signal_wire73 = 32'h00000006;
	wire [31:0] signal_wire74 = 32'h00000007;
	wire [31:0] signal_wire75 = 32'h00000008;
	wire [31:0] signal_wire76 = 32'h00000009;
	wire [31:0] signal_wire77 = 32'h0000000a;
	wire [31:0] signal_wire78 = 32'h0000000b;
	wire [31:0] signal_wire79 = 32'h0000000c;
	wire [31:0] signal_wire80 = 32'h0000000d;
	wire [31:0] signal_wire81 = 32'h0000000e;
	wire [31:0] signal_wire82 = 32'h0000000f;
	wire [31:0] signal_wire83 = 32'h00000010;
	wire [31:0] signal_wire84 = 32'h00000011;
	wire [15:0] signal_wire85 = 16'h0008;
	wire [15:0] signal_wire86 = 16'h0008;
	wire [15:0] signal_wire87 = 16'h0008;
	wire [15:0] signal_wire88 = 16'h0008;
	wire [15:0] signal_wire89 = 16'h0007;
	wire [15:0] signal_wire90 = 16'h0008;
	wire [15:0] signal_wire91 = 16'h000e;
	wire [15:0] signal_wire92 = 16'h0010;
	wire [15:0] signal_wire93 = 16'h0010;
	wire [15:0] signal_wire94 = 16'b0;
	wire [15:0] signal_wire95 = 16'b0;
	wire [15:0] signal_wire96 = 16'b0;
	wire [15:0] signal_wire97 = 16'b0;
	wire [15:0] signal_wire98 = 16'b0;
	wire [15:0] signal_wire99 = 16'b0;
	wire [15:0] signal_wire100 = 16'b0;
	wire [15:0] signal_wire101 = 16'b0;
	wire [15:0] signal_wire102 = 16'b0;
	wire [15:0] signal_wire103 = 16'b0;
	wire [15:0] signal_wire104 = 16'b0;
	wire [15:0] signal_wire105 = 16'b0;
	wire [15:0] signal_wire106 = 16'b0;
	wire [15:0] signal_wire107 = 16'b0;
	wire [15:0] signal_wire108 = 16'b0;
	wire [15:0] signal_wire109 = 16'b0;
	wire [15:0] signal_wire110 = 16'b0;
	wire [15:0] signal_wire111 = 16'b0;
	wire [15:0] signal_wire112 = 16'b0;
	wire [15:0] signal_wire113 = 16'b0;
	wire [15:0] signal_wire114 = 16'b0;
	wire [15:0] signal_wire115 = 16'b0;
	wire [15:0] signal_wire116 = 16'b0;
	wire [15:0] signal_wire117 = 16'b0;
	wire [15:0] signal_wire118 = 16'b0;
	wire [15:0] signal_wire119 = 16'b0;
	wire [15:0] signal_wire120 = 16'b0;
	wire [15:0] signal_wire121 = 16'b0;
	wire [15:0] signal_wire122 = 16'b0;
	wire [15:0] signal_wire123 = 16'b0;
	wire [15:0] signal_wire124 = 16'b0;
	wire [15:0] signal_wire125 = 16'b0;
	wire [15:0] signal_wire126 = 16'b0;
	wire [15:0] signal_wire127 = 16'b0;
	wire [15:0] signal_wire128 = 16'b0;
	wire [15:0] signal_wire129 = 16'b0;
	wire [15:0] signal_wire130 = 16'b0;
	wire [15:0] signal_wire131 = 16'b0;
	wire [15:0] signal_wire132 = 16'b0;
	wire [15:0] signal_wire133 = 16'b0;
	wire [15:0] signal_wire134 = 16'b0;
	wire [15:0] signal_wire135 = 16'b0;
	wire [15:0] signal_wire136 = 16'b0;
	wire [15:0] signal_wire137 = 16'b0;
	wire [15:0] signal_wire138 = 16'b0;
	wire [15:0] signal_wire139 = 16'b0;
	wire [15:0] signal_wire140 = 16'b0;
	wire [15:0] signal_wire141 = 16'b0;
	wire [15:0] signal_wire142 = 16'b0;

	auk_pac_mrx_mw	auk_pac_mrx_mw_inst(
		.clka(a_rfclk),
		.reseta(a_rreset_n),
		.dpav_ina(signal_wire0),
		.ppav_ina(signal_wire1),
		.spav_ina(signal_wire2),
		.addr_ina(signal_wire3),
		.wr_ina(signal_wire4),
		.val_ina(a_rval),
		.sx_ina(signal_wire5),
		.data_ina(a_rdat),
		.sop_ina(a_rsop),
		.eop_ina(a_reop),
		.err_ina(a_rerr),
		.prty_ina(signal_wire6),
		.mod_ina(a_rmod),
		.clkb1(b_clk),
		.resetb1(b_reset_n),
		.dpav_inb1(signal_wire7),
		.ppav_inb1(signal_wire8),
		.spav_inb1(signal_wire9),
		.dav_inb1(signal_wire10),
		.addr_inb1(signal_wire11),
		.rd_inb1(b_ena),
		.clkb2(signal_wire12),
		.resetb2(signal_wire13),
		.dpav_inb2(signal_wire14),
		.ppav_inb2(signal_wire15),
		.spav_inb2(signal_wire16),
		.dav_inb2(signal_wire17),
		.addr_inb2(signal_wire18),
		.rd_inb2(signal_wire19),
		.clkb3(signal_wire20),
		.resetb3(signal_wire21),
		.dpav_inb3(signal_wire22),
		.ppav_inb3(signal_wire23),
		.spav_inb3(signal_wire24),
		.dav_inb3(signal_wire25),
		.addr_inb3(signal_wire26),
		.rd_inb3(signal_wire27),
		.clkb4(signal_wire28),
		.resetb4(signal_wire29),
		.dpav_inb4(signal_wire30),
		.ppav_inb4(signal_wire31),
		.spav_inb4(signal_wire32),
		.dav_inb4(signal_wire33),
		.addr_inb4(signal_wire34),
		.rd_inb4(signal_wire35),
		.clkb5(signal_wire36),
		.resetb5(signal_wire37),
		.dpav_inb5(signal_wire38),
		.ppav_inb5(signal_wire39),
		.spav_inb5(signal_wire40),
		.dav_inb5(signal_wire41),
		.addr_inb5(signal_wire42),
		.rd_inb5(signal_wire43),
		.clkb6(signal_wire44),
		.resetb6(signal_wire45),
		.dpav_inb6(signal_wire46),
		.ppav_inb6(signal_wire47),
		.spav_inb6(signal_wire48),
		.dav_inb6(signal_wire49),
		.addr_inb6(signal_wire50),
		.rd_inb6(signal_wire51),
		.clkb7(signal_wire52),
		.resetb7(signal_wire53),
		.dpav_inb7(signal_wire54),
		.ppav_inb7(signal_wire55),
		.spav_inb7(signal_wire56),
		.dav_inb7(signal_wire57),
		.addr_inb7(signal_wire58),
		.rd_inb7(signal_wire59),
		.clkb8(signal_wire60),
		.resetb8(signal_wire61),
		.dpav_inb8(signal_wire62),
		.ppav_inb8(signal_wire63),
		.spav_inb8(signal_wire64),
		.dav_inb8(signal_wire65),
		.addr_inb8(signal_wire66),
		.rd_inb8(signal_wire67),
		.custom_ina0(signal_wire68),
		.custom_ina1(signal_wire69),
		.custom_inb1(signal_wire70),
		.custom_ina2(signal_wire71),
		.custom_inb2(signal_wire72),
		.custom_ina3(signal_wire73),
		.custom_inb3(signal_wire74),
		.custom_ina4(signal_wire75),
		.custom_inb4(signal_wire76),
		.custom_ina5(signal_wire77),
		.custom_inb5(signal_wire78),
		.custom_ina6(signal_wire79),
		.custom_inb6(signal_wire80),
		.custom_ina7(signal_wire81),
		.custom_inb7(signal_wire82),
		.custom_ina8(signal_wire83),
		.custom_inb8(signal_wire84),
		.a_fifo_burst(signal_wire85),
		.a_remote_burst(signal_wire86),
		.b1_fifo_burst(signal_wire87),
		.b1_remote_burst(signal_wire88),
		.b1_master_full_thresh(signal_wire89),
		.b1_empty_on_thresh(signal_wire90),
		.b1_empty_off_thresh(signal_wire91),
		.b1_full_on_thresh(signal_wire92),
		.b1_full_off_thresh(signal_wire93),
		.b2_fifo_burst(signal_wire94),
		.b2_remote_burst(signal_wire95),
		.b2_master_full_thresh(signal_wire96),
		.b2_empty_on_thresh(signal_wire97),
		.b2_empty_off_thresh(signal_wire98),
		.b2_full_on_thresh(signal_wire99),
		.b2_full_off_thresh(signal_wire100),
		.b3_fifo_burst(signal_wire101),
		.b3_remote_burst(signal_wire102),
		.b3_master_full_thresh(signal_wire103),
		.b3_empty_on_thresh(signal_wire104),
		.b3_empty_off_thresh(signal_wire105),
		.b3_full_on_thresh(signal_wire106),
		.b3_full_off_thresh(signal_wire107),
		.b4_fifo_burst(signal_wire108),
		.b4_remote_burst(signal_wire109),
		.b4_master_full_thresh(signal_wire110),
		.b4_empty_on_thresh(signal_wire111),
		.b4_empty_off_thresh(signal_wire112),
		.b4_full_on_thresh(signal_wire113),
		.b4_full_off_thresh(signal_wire114),
		.b5_fifo_burst(signal_wire115),
		.b5_remote_burst(signal_wire116),
		.b5_master_full_thresh(signal_wire117),
		.b5_empty_on_thresh(signal_wire118),
		.b5_empty_off_thresh(signal_wire119),
		.b5_full_on_thresh(signal_wire120),
		.b5_full_off_thresh(signal_wire121),
		.b6_fifo_burst(signal_wire122),
		.b6_remote_burst(signal_wire123),
		.b6_master_full_thresh(signal_wire124),
		.b6_empty_on_thresh(signal_wire125),
		.b6_empty_off_thresh(signal_wire126),
		.b6_full_on_thresh(signal_wire127),
		.b6_full_off_thresh(signal_wire128),
		.b7_fifo_burst(signal_wire129),
		.b7_remote_burst(signal_wire130),
		.b7_master_full_thresh(signal_wire131),
		.b7_empty_on_thresh(signal_wire132),
		.b7_empty_off_thresh(signal_wire133),
		.b7_full_on_thresh(signal_wire134),
		.b7_full_off_thresh(signal_wire135),
		.b8_fifo_burst(signal_wire136),
		.b8_remote_burst(signal_wire137),
		.b8_master_full_thresh(signal_wire138),
		.b8_empty_on_thresh(signal_wire139),
		.b8_empty_off_thresh(signal_wire140),
		.b8_full_on_thresh(signal_wire141),
		.b8_full_off_thresh(signal_wire142),
		.rd_outa(a_renb),
		.dav_outb1(b_dav),
		.val_outb1(b_val),
		.data_outb1(b_dat),
		.sop_outb1(b_sop),
		.eop_outb1(b_eop),
		.err_outb1(b_err),
		.mod_outb1(b_mty));

	defparam
		auk_pac_mrx_mw_inst.gio_number_of_interface_a = 1,
		auk_pac_mrx_mw_inst.gio_number_of_interface_b = 1,
		auk_pac_mrx_mw_inst.gio_number_of_fifo = 1,
		auk_pac_mrx_mw_inst.gio_bus_mode = "1 2",
		auk_pac_mrx_mw_inst.gio_bus_level = "2 2",
		auk_pac_mrx_mw_inst.gio_bus_type = "0 1",
		auk_pac_mrx_mw_inst.gio_bus_direction = "1 0",
		auk_pac_mrx_mw_inst.gio_address_channels = "1 1",
		auk_pac_mrx_mw_inst.gio_address_range = "0 1",
		auk_pac_mrx_mw_inst.gio_address_width = "0 0",
		auk_pac_mrx_mw_inst.gio_address_style = "0 0",
		auk_pac_mrx_mw_inst.gio_base_address = "0 0",
		auk_pac_mrx_mw_inst.gio_address_mask = "0 0",
		auk_pac_mrx_mw_inst.gio_transfer_mode = "0 0",
		auk_pac_mrx_mw_inst.gio_dpav_range = "1 0",
		auk_pac_mrx_mw_inst.gio_spav_present = "0 0",
		auk_pac_mrx_mw_inst.gio_ppav_present = "0 0",
		auk_pac_mrx_mw_inst.gio_ddav_range = "1 1",
		auk_pac_mrx_mw_inst.gio_sx_present = "0 0",
		auk_pac_mrx_mw_inst.gio_val_present = "1 1",
		auk_pac_mrx_mw_inst.gio_eop_present = "1 1",
		auk_pac_mrx_mw_inst.gio_mod_present = "1 1",
		auk_pac_mrx_mw_inst.gio_data_width = "32 32",
		auk_pac_mrx_mw_inst.gio_prty_error_mode = "1 1",
		auk_pac_mrx_mw_inst.gio_prty_present = "0 0",
		auk_pac_mrx_mw_inst.gio_prty_mode = "0 0",
		auk_pac_mrx_mw_inst.gfifo_addr_range = "0 0",
		auk_pac_mrx_mw_inst.gfifo_depth = "0 128",
		auk_pac_mrx_mw_inst.gfifo_sync = "0 0",
		auk_pac_mrx_mw_inst.gio_fifo_burst = "8 8",
		auk_pac_mrx_mw_inst.gio_remote_burst = "8 8",
		auk_pac_mrx_mw_inst.gio_full_on_thresh = "0 16",
		auk_pac_mrx_mw_inst.gio_full_off_thresh = "0 16",
		auk_pac_mrx_mw_inst.gio_empty_on_thresh = "0 8",
		auk_pac_mrx_mw_inst.gio_empty_off_thresh = "0 14",
		auk_pac_mrx_mw_inst.gio_master_full_thresh = "0 7",
		auk_pac_mrx_mw_inst.gio_master_empty_thresh = "0 0",
		auk_pac_mrx_mw_inst.gio_mux_present = "1 0",
		auk_pac_mrx_mw_inst.gio_conva_present = "0 1",
		auk_pac_mrx_mw_inst.gio_convb_present = "0 0",
		auk_pac_mrx_mw_inst.gfifo_present = "0 1",
		auk_pac_mrx_mw_inst.gio_master_rd_dav_present = "1 1",
		auk_pac_mrx_mw_inst.gio_master_val_in_present = "1 1",
		auk_pac_mrx_mw_inst.gio_master_halt_on_val = "1 1",
		auk_pac_mrx_mw_inst.gio_data_out_zero = "0 0",
		auk_pac_mrx_mw_inst.gio_dumb_mode = "0 0",
		auk_pac_mrx_mw_inst.gio_speculative_read = "1 1",
		auk_pac_mrx_mw_inst.gio_custom_mode = "0 0",
		auk_pac_mrx_mw_inst.gio_reset = "0 0",
		auk_pac_mrx_mw_inst.gio_usesignals = 0,
		auk_pac_mrx_mw_inst.gdevice = 7,
		auk_pac_mrx_mw_inst.gdpav_width_out0 = 1,
		auk_pac_mrx_mw_inst.gaddr_width_out0 = 1,
		auk_pac_mrx_mw_inst.gdata_width0 = 32,
		auk_pac_mrx_mw_inst.gmod_width0 = 2,
		auk_pac_mrx_mw_inst.gdpav_width_out1 = 1,
		auk_pac_mrx_mw_inst.gaddr_width_out1 = 1,
		auk_pac_mrx_mw_inst.gdata_width1 = 32,
		auk_pac_mrx_mw_inst.gmod_width1 = 2,
		auk_pac_mrx_mw_inst.gdpav_width_in2 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_out2 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in2 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_out2 = 8,
		auk_pac_mrx_mw_inst.gdata_width2 = 64,
		auk_pac_mrx_mw_inst.gmod_width2 = 4,
		auk_pac_mrx_mw_inst.gdpav_width_in3 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_out3 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in3 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_out3 = 8,
		auk_pac_mrx_mw_inst.gdata_width3 = 64,
		auk_pac_mrx_mw_inst.gmod_width3 = 4,
		auk_pac_mrx_mw_inst.gdpav_width_in4 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_out4 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in4 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_out4 = 8,
		auk_pac_mrx_mw_inst.gdata_width4 = 64,
		auk_pac_mrx_mw_inst.gmod_width4 = 4,
		auk_pac_mrx_mw_inst.gdpav_width_in5 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_out5 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in5 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_out5 = 8,
		auk_pac_mrx_mw_inst.gdata_width5 = 64,
		auk_pac_mrx_mw_inst.gmod_width5 = 4,
		auk_pac_mrx_mw_inst.gdpav_width_in6 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_out6 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in6 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_out6 = 8,
		auk_pac_mrx_mw_inst.gdata_width6 = 64,
		auk_pac_mrx_mw_inst.gmod_width6 = 4,
		auk_pac_mrx_mw_inst.gdpav_width_in7 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_out7 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in7 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_out7 = 8,
		auk_pac_mrx_mw_inst.gdata_width7 = 64,
		auk_pac_mrx_mw_inst.gmod_width7 = 4,
		auk_pac_mrx_mw_inst.gdpav_width_in8 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_out8 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in8 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_out8 = 8,
		auk_pac_mrx_mw_inst.gdata_width8 = 64,
		auk_pac_mrx_mw_inst.gmod_width8 = 4,
		auk_pac_mrx_mw_inst.gdpav_width_in0 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in0 = 8,
		auk_pac_mrx_mw_inst.gdpav_width_in1 = 8,
		auk_pac_mrx_mw_inst.gaddr_width_in1 = 8;
endmodule

// =========================================================
// POS-PHY Level 2 and 3 Compiler Wizard Data
// ===============================
// DO NOT EDIT FOLLOWING DATA
// @Altera, IP Toolbench@
// Warning: If you modify this section, POS-PHY Level 2 and 3 Compiler Wizard may not be able to reproduce your chosen configuration.
// 
// Retrieval info: <?xml version="1.0"?>
// Retrieval info: <MEGACORE title="POS-PHY Level 2 and 3 Compiler"  version="1.4.1"  iptb_version="v1.2.11 build48"  format_version="120" >
// Retrieval info:  <NETLIST_SECTION active_core="auk_pac_mrx_mw" >
// Retrieval info:   <STATIC_SECTION>
// Retrieval info:    <PRIVATES>
// Retrieval info:     <NAMESPACE name = "parameterization">
// Retrieval info:      <PRIVATE name = "devicefamily" value="Cyclone II"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "BUS_DIRECTION" value="RX"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "B_PORT_COUNT" value="1"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "COMMON_B_CLK_AND_RESET" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_INTERFACE_TYPE" value="PL3_LNK"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_BUS_WIDTH" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_PARITY_MODE" value="NONE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_PAR_ERR_ON_ERR_PIN" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_THRESHOLD" value="64"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_REMOTE_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_ADDRESS_MODE" value="DIRECT_SINGLE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_SX_ALWAYS" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_BASE_ADDRESS" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_DISABLE_SXPA" value="1"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_A_FIFO_SYNC" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "FIFO_OVERFLOW" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "gdevice" value="7"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_INTERFACE_TYPE" value="ATL_SLV"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_BUS_WIDTH" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_PARITY_MODE" value="NONE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_PAR_ERR_ON_ERR_PIN" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_NO_FIFO" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_ADD_CONVB" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_SIZE" value="512"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_THRESHOLD" value="64"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_REMOTE_BURST" value="32"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_ADDRESS_MODE" value="DIRECT_SINGLE"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_SX_ALWAYS" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_BASE_ADDRESS" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_DISABLE_SXPA" value="1"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "PORT_B1_FIFO_SYNC" value="0"  type="BOOLEAN"  enable="1" />
// Retrieval info:      <PRIVATE name = "gio_custom" value="0 0 0 0 0 0 0 0 0"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "gio_usesignals" value="0"  type="INTEGER"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "simgen_enable">
// Retrieval info:      <PRIVATE name = "language" value="Verilog HDL"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "simgen">
// Retrieval info:      <PRIVATE name = "filename" value="spi3_rx.vo"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "quartus_settings">
// Retrieval info:      <PRIVATE name = "DEVICE" value="AUTO"  type="STRING"  enable="1" />
// Retrieval info:      <PRIVATE name = "FAMILY" value="Cyclone II"  type="STRING"  enable="1" />
// Retrieval info:     </NAMESPACE>
// Retrieval info:     <NAMESPACE name = "serializer"/>
// Retrieval info:    </PRIVATES>
// Retrieval info:    <FILES/>
// Retrieval info:    <CONSTANTS>
// Retrieval info:     <CONSTANT name = "gio_number_of_interface_a" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gio_number_of_interface_b" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gio_number_of_fifo" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gio_bus_mode" value="1 2"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_bus_level" value="2 2"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_bus_type" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_bus_direction" value="1 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_channels" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_range" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_width" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_style" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_base_address" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_address_mask" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_transfer_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_dpav_range" value="1 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_spav_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_ppav_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_ddav_range" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_sx_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_val_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_eop_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_mod_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_data_width" value="32 32"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_prty_error_mode" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_prty_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_prty_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_addr_range" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_depth" value="0 128"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_sync" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_fifo_burst" value="8 8"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_remote_burst" value="8 8"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_full_on_thresh" value="0 16"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_full_off_thresh" value="0 16"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_empty_on_thresh" value="0 8"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_empty_off_thresh" value="0 14"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_full_thresh" value="0 7"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_empty_thresh" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_mux_present" value="1 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_conva_present" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_convb_present" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gfifo_present" value="0 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_rd_dav_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_val_in_present" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_master_halt_on_val" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_data_out_zero" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_dumb_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_speculative_read" value="1 1"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_custom_mode" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_reset" value="0 0"  type="STRING" />
// Retrieval info:     <CONSTANT name = "gio_usesignals" value="0"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdevice" value="7"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out0" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out0" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width0" value="32"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width0" value="2"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out1" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out1" value="1"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width1" value="32"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width1" value="2"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out2" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width2" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width2" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out3" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width3" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width3" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out4" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width4" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width4" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out5" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width5" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width5" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out6" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width6" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width6" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out7" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width7" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width7" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_out8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_out8" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdata_width8" value="64"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gmod_width8" value="4"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in0" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in0" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gdpav_width_in1" value="8"  type="INTEGER" />
// Retrieval info:     <CONSTANT name = "gaddr_width_in1" value="8"  type="INTEGER" />
// Retrieval info:    </CONSTANTS>
// Retrieval info:    <PORTS>
// Retrieval info:     <PORT name = "clka" direction="INPUT"  connect_to="a_rfclk"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "reseta" direction="INPUT"  connect_to="a_rreset_n"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "wr_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_ina" direction="INPUT"  connect_to="a_rval"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "sx_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_ina" direction="INPUT"  connect_to="a_rdat"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_ina" direction="INPUT"  connect_to="a_rsop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_ina" direction="INPUT"  connect_to="a_reop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_ina" direction="INPUT"  connect_to="a_rerr"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "prty_ina" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_ina" direction="INPUT"  connect_to="a_rmod"  default="NODEFVAL"  high_width="1"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_outa" direction="OUTPUT"  connect_to="a_renb"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb1" direction="INPUT"  connect_to="b_clk"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb1" direction="INPUT"  connect_to="b_reset_n"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb1" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb1" direction="INPUT"  connect_to="b_ena"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_outb1" direction="OUTPUT"  connect_to="b_dav"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "val_outb1" direction="OUTPUT"  connect_to="b_val"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "data_outb1" direction="OUTPUT"  connect_to="b_dat"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "sop_outb1" direction="OUTPUT"  connect_to="b_sop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "eop_outb1" direction="OUTPUT"  connect_to="b_eop"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "err_outb1" direction="OUTPUT"  connect_to="b_err"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "mod_outb1" direction="OUTPUT"  connect_to="b_mty"  default="NODEFVAL"  high_width="1"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "clkb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb2" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb3" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb4" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb5" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb6" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb7" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "clkb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "resetb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dpav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "ppav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "spav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "dav_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "addr_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="7"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "rd_inb8" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  width="1"  description="" />
// Retrieval info:     <PORT name = "custom_ina0" direction="INPUT"  connect_to=" 1"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina1" direction="INPUT"  connect_to=" 2"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb1" direction="INPUT"  connect_to=" 3"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina2" direction="INPUT"  connect_to=" 4"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb2" direction="INPUT"  connect_to=" 5"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina3" direction="INPUT"  connect_to=" 6"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb3" direction="INPUT"  connect_to=" 7"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina4" direction="INPUT"  connect_to=" 8"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb4" direction="INPUT"  connect_to=" 9"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina5" direction="INPUT"  connect_to=" 10"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb5" direction="INPUT"  connect_to=" 11"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina6" direction="INPUT"  connect_to=" 12"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb6" direction="INPUT"  connect_to=" 13"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina7" direction="INPUT"  connect_to=" 14"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb7" direction="INPUT"  connect_to=" 15"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_ina8" direction="INPUT"  connect_to=" 16"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "custom_inb8" direction="INPUT"  connect_to=" 17"  default="NODEFVAL"  high_width="31"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "a_fifo_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "a_remote_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_fifo_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_remote_burst" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_master_full_thresh" direction="INPUT"  connect_to="7"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_empty_on_thresh" direction="INPUT"  connect_to="8"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_empty_off_thresh" direction="INPUT"  connect_to="14"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_full_on_thresh" direction="INPUT"  connect_to="16"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b1_full_off_thresh" direction="INPUT"  connect_to="16"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b2_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b3_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b4_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b5_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b6_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b7_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_fifo_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_remote_burst" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_master_full_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_empty_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_empty_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_full_on_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:     <PORT name = "b8_full_off_thresh" direction="INPUT"  connect_to="GND"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
// Retrieval info:    </PORTS>
// Retrieval info:    <LIBRARIES/>
// Retrieval info:   </STATIC_SECTION>
// Retrieval info:  </NETLIST_SECTION>
// Retrieval info: </MEGACORE>
// =========================================================
// RELATED_FILES: spi3_rx.v;
// IPFS_FILES: none;
// =========================================================
